# model_config.yaml used in OrtSessionWarpper
model:
  path: "models/NAFNet-w32.onnx"
  backend: "onnxruntime"
  padder_size: 16 # 暂时没用上
  shape: [576, 576] # h, w 目前要求所有图像size小于该尺寸才可以触发全局缓存，后续可以添加缓存桶，一次提供多个常用的shape，让图像自动padding到最适合的桶进行推理，保证高效
  batch: 1 # 推理过程中缓存的batch
  gpu: 1
  session_options:
    trt_fp16_enable: "0" # ["0", "1"] 当且仅当TensorrtExecutionProvider有效时可用，默认fp32推理
    execution_providers: ["TensorrtExecutionProvider", "CUDAExecutionProvider"]
    graph_optimization_level: "ORT_ENABLE_ALL"
    intra_op_num_threads: 4
    inter_op_num_threads: 1
    execution_mode: "ORT_SEQUENTIAL"
    log_severity_level: "ERROR"
    enable_profiling: false,
    optimized_model_path: "" # 默认保存到 optimize_xxx.onnx
  warm_up: 3

preprocess:
  auto_aspect_ratio: true
  pad_color: [114, 114, 114]
  normalize:
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]   # YOLOv8 只做 /255，等价于 std=1
  bgr_to_rgb: true

# postprocess:
#   conf_threshold: 0.25
#   nms_threshold: 0.45
#   max_detections: 300